Add support for namespace settings in `kubectl` executor (#664)
- add e2e/unit-test coverage to ensure no regression
- add `namespace` property feature
- extracted the `kubectl` pkg to dedicated struct **(code quality)**
- UX enhancements in responses:

   - **Get forbidden resource**
      - previous: `"Command not supported. Please run /botkubehelp to see supported commands."`
      - now: `"Sorry, the kubectl command is not authorized to work with 'ingress' resources on cluster 'sample'."`

  - **Not authorized channel but cluster is**
      - previous: no response
      - now: `"Sorry, this channel is not authorized to execute kubectl command on cluster 'sample'."`
          
   - **Specify invalid command**
      - previous: "Command not supported. Please run /botkubehelp to see supported commands."
      - now:
        ```
        Cluster: sample
        You must specify the type of resource to get. Use "kubectl api-resources" for a complete list of supported resources.
  
			  error: Required resource not specified.
			  Use "kubectl explain <resource>" for a detailed description of that resource (e.g. kubectl explain pods).
			  See 'kubectl get -h' for help and examples
			  while executing kubectl command: exit status 1
        ```    
  - **Specify forbidden namespace**
      - previous: no response
      - now: `"Sorry, the kubectl command cannot be executed in the 'team-b' Namespace on cluster 'sample'."`
      

  - **Not the target cluster**
      - previous: no response
      - now: no response